server {
    listen 443 ssl;
    server_name converter-temperature.duckdns.org www.converter-temperature.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/converter-temperature.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/converter-temperature.duckdns.org/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}

# Opcional: redirecionar HTTP → HTTPS
server {
    listen 80;
    server_name converter-temperature.duckdns.org www.converter-temperature.duckdns.org;

    location /.well-known/acme-challenge/ {
        alias /var/www/certbot/.well-known/acme-challenge/;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
