name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy app
        run: |
          cd /opt/apps/conversor-temperatura
          git pull
          docker build -t conversor-temperatura .
          docker rm -f conversor-temperatura || true
          docker run -d --name conversor-temperatura -p 80:80 conversor-temperatura